name: Android build

on:
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
              distribution: 'zulu' # See 'Supported distributions' for available options
              java-version: '21'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn

      - name: Install dependencies
        run: yarn --cwd example --frozen-lockfile

      - name: Write local.properties
        run: echo MAPS_API_KEY=your_api_key_here >> example/android/local.properties

      - name: Build Android
        run: cd example/android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug
